# Variable

how to store time in a variable

In [2]:
from datetime import datetime

now = datetime.now()
print(now)

2026-04-08 00:22:50.882334


In [3]:
type(now)

datetime.datetime

now, if i want to convert it to string:

In [5]:
string_time = now.strftime("%Y-%m-%d %H:%M:%S")
print(string_time)
print(type(string_time))

2026-04-08 00:22:50
<class 'str'>


In [2]:
# count frequnecy of each element in a list using dictionary:

dictionary = {}
list1 = list(input().split())
for num in list1:
    num = int(num)
    if num in dictionary:
        dictionary[num] += 1
    else:
        dictionary[num] = 1
print(dictionary)

{1: 2, 2: 2, 3: 2, 4: 2}


In [3]:
# using numpy & pandas:

import numpy as np
import pandas as pd

#numpy array:
names = np.array(["alice", "bob", "david", "maya"])
scores = np.array([85, 90, 78, 92])

# create dictionary:
data = {
    "name" : names,
    "score" : scores
}

# convert to pandas dataframe:

df = pd.DataFrame(data)
print(df)

    name  score
0  alice     85
1    bob     90
2  david     78
3   maya     92


In [4]:
# again for practice:

names_ = np.array(["preta", "pranta"])
scores_ = np.array([90, 92])

data_ = {
    "name": names_,
    "score": scores_
}

df2 = pd.DataFrame(data_)
df2

,name,score
0,preta,90
1,pranta,92


# Function

In [5]:
def create_table():
    #numpy array:
    names = np.array(["alice", "bob", "david", "maya"])
    scores = np.array([85, 90, 78, 92])

    # create dictionary:
    data = {
    "name" : names,
    "score" : scores
    }

    # convert to pandas dataframe:

    df = pd.DataFrame(data)
    return df

print(create_table())

    name  score
0  alice     85
1    bob     90
2  david     78
3   maya     92


# Iterator

In [ ]:

arr = np.array([12,32,42,13,453,12])
arr_iter = iter(arr)

print(next(arr_iter))
print(next(arr_iter))
print(next(arr_iter))
print(next(arr_iter))


12
32
42
13


in here the outputs are showing in serialy. but in sets or dictionaries, it will not show in serial

In [11]:
df = pd.DataFrame(
    {
        "A" : [1,2,3],
        "B" : [4,5,6]
    }
)
print(df)

   A  B
0  1  4
1  2  5
2  3  6


In [12]:
# iterate:
for row in df.itertuples():
    print(row)

Pandas(Index=0, A=1, B=4)
Pandas(Index=1, A=2, B=5)
Pandas(Index=2, A=3, B=6)


# Generator



In [17]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:


def data_loader(batch_size, data):
    for i in range(0, len(data), batch_size):
        yield data[i: i+batch_size]      # yield -> return chunk, not whole data

data = np.arange(20)

loader = data_loader(5, data)

print(next(loader))

[0 1 2 3 4]


In [20]:
print(next(loader))

[5 6 7 8 9]


# Filter

In [21]:
data = np.array([23,12,53,643,12,432,12,34])

df = list(filter(lambda x: x>30, data))

In [ ]:
print(df)
print(*df)

"""
ekhane * ,  list টাকে unpack করে দেয়।
অর্থাৎ list এর প্রতিটা element আলাদা argument হিসেবে print() এ পাঠায়।
"""

[np.int64(53), np.int64(643), np.int64(432), np.int64(34)]
53 643 432 34


# Dataframe

In [28]:
df = pd.DataFrame(
    {
        "name" : ['Alice', 'Sob'],
        "score" : [34, 23]
    }
)

print(df)

    name  score
0  Alice     34
1    Sob     23


In [33]:
high_score = df[df['score']>30]
print(high_score)

    name  score
0  Alice     34


In [30]:
filtered_columns = df.filter(regex = "S")
print(filtered_columns)

Empty DataFrame
Columns: []
Index: [0, 1]
