Array Creation and Manipulation
- Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
- Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0. [ Home work]

In [2]:
import numpy as np
a = np.random.randint(1,21,(5,5))
a[:,2] = 1
print(a)

[[20 12  1 15 18]
 [15 15  1  5  9]
 [20  3  1 14  9]
 [ 5  6  1  7 17]
 [19  9  1 10 17]]


In [6]:
b = np.random.randint(1,17,(4,4))
np.fill_diagonal(b,0)
print(b)

[[ 0  6  4  7]
 [12  0 15  7]
 [ 9  4  0  2]
 [ 7  2  4  0]]


Array Indexing and Slicing
- Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
- Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border. (HW)

In [8]:
c = np.random.randint(1,36, (6,6))

d = c[2:5, 1:4]
print(d)

[[19 24 31]
 [ 4 24  6]
 [16  1 10]]


In [12]:
arr = np.random.randint(0, 100, size=(5, 5))

a= arr[:,0]
b = arr[:, -1]
c = arr[0,:]
d = arr[-1,:]
border_elements = np.concatenate((a, b, c, d))
print(border_elements)

[69 99 87 58 38 65 28 24 97 91 69 14 81 70 65 38 64 26 43 91]


Array Operations
- Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
- Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [13]:
arr1 = np.random.randint(0, 100, size=(3,4))
arr2 = np.random.randint(0, 100, size=(3,4))

add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2

In [15]:
arr = np.random.randint(1, 17, size=(4,4))
print(np.sum(arr, axis=0))  # Column-wise sum
print(np.sum(arr, axis=1))  # Row-wise sum

[29 41 24 39]
[38 33 36 26]


Statistical Operations
- Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array. ( HW)

In [16]:
arr = np.random.randint(0, 100, size=(5, 5))


mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)
var_val = np.var(arr)

Boolean Indexing
- Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [18]:
a = np.random.randint(1, 21, size=(4, 4))
a[a>10] = 10
print(a)

[[10 10 10  8]
 [10 10 10 10]
 [10 10  1  3]
 [10 10 10 10]]


Easy https://www.deep-ml.com/problems/3