### ndarray creation from existing data

In [2]:
import numpy as np

In [3]:
# From list
list1 = [10,20,30,40,50, 60.4]

arr = np.array(list1)
print(arr)
print(type(arr))
print(arr.dtype)    # what type of element is stored in array
print(arr.shape)    # dimention of array
print(arr.ndim)     # number of dimension

[10.  20.  30.  40.  50.  60.4]
<class 'numpy.ndarray'>
float64
(6,)
1


In [4]:
list2 = [10,True, "Hello", 3.14]    # mixed data type
arr2 = np.array(list2)
print(arr2)
print(type(arr2))
print(arr2.dtype)    # what type of element is stored in array -> unicode string of 32 bit

['10' 'True' 'Hello' '3.14']
<class 'numpy.ndarray'>
<U32


In [5]:
list3 = [[1,2,3], 
         [4,5,6], 
         [7,8,9]]
arr3 = np.array(list3)
print(arr3)
print(type(arr3))
print(arr3.dtype)
print(arr3.shape)    # dimention of array
print(arr3.ndim)     # number of dimension

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2


👉 এটা 2D array (matrix)

- 1st dimension → row
- 2nd dimension → column
<br>
dimension মানে কয়টা direction/axis আছে. so ndim = 2

In [6]:
# from tuple
tuple1 = (10,20,30,40,50)

arr4 = np.array(tuple1)
print(arr4)
print(type(arr4))
print(arr4.dtype)
print(arr4.ndim)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
1


In [7]:
# from set
set1 = {10,20,30,40,50}
arr5 = np.array(set1)
print(arr5)
print(type(arr5))
print(arr5.dtype)   # object -> because set is unordered collection of unique elements
print(arr5.ndim)    # 0 -> because set is unordered collection of unique elements

{50, 20, 40, 10, 30}
<class 'numpy.ndarray'>
object
0


In [8]:
# from object to make it 'int'
arr6 = np.array(list(set1))
print(arr6)
print(type(arr6))
print(arr6.dtype)
print(arr6.ndim)    # 1 -> because now it is an array of integers

[50 20 40 10 30]
<class 'numpy.ndarray'>
int64
1


In [9]:
# from dictionary
dict1 = {'a': 1, 'b': 2, 'c': 3}
arr7 = np.array(dict1)
print(arr7)
print(type(arr7))
print(arr7.dtype)
print(arr7.ndim)    

{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>
object
0


In [10]:
dict2 = {'a': 1, 'b': 2, 'c': 3}
print(dict2.keys())
print(dict2.values())
print(dict2.items())

dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])


In [11]:
keys = dict2.keys()
values = dict2.values()
items = dict2.items()

# keys to ndarray
arr8 = np.array(keys)
print(arr8)
print(type(arr8))
print(arr8.dtype)
print(arr8.ndim)

dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
object
0


In [12]:
# values to ndarray
arr9 = np.array(list(values))
print(arr9)
print(type(arr9))
print(arr9.dtype)
print(arr9.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
1


In [13]:
# items to ndarray
arr10 = np.array(list(items))
print(arr10)
print(type(arr10))
print(arr10.dtype)
print(arr10.ndim)


[['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>
<U21
2


### Ndarray generation with random values

In [ ]:
arr = np.random.rand(2,3) # generate random numbers between 0 and 1 in a 2x3 array
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[0.25658653 0.5695396  0.75939061]
 [0.06909243 0.93273933 0.66299691]]
<class 'numpy.ndarray'>
float64
(2, 3)
2


In [ ]:
# generate random integer values
arr = np.random.randint(1, 10, size=(2,3)) # generate random integers between 1 and 10 in a 2x3 array
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[9 5 8]
 [5 7 7]]
<class 'numpy.ndarray'>
int32
(2, 3)
2


In [16]:
# genereate random float values
arr = np.random.uniform(50, 100, size=(2,3)) # generate random floats between 50 and 100 in a 2x3 array
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[69.97073812 70.79403206 98.43201779]
 [56.49446204 64.73709877 98.34004091]]
<class 'numpy.ndarray'>
float64
(2, 3)
2


### array creation with range function

In [20]:
arr = np.arange(1, 10, 1) # generate an array of integers from 1 to 10 with a step of 1
print(arr)


[1 2 3 4 5 6 7 8 9]


In [23]:
arr = np.arange(1, 10, 1)
mat = arr.reshape(3,3) # reshape the array to 3x3

print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# np.linespace(start, stop(included in output), num=50) -> generate num evenly spaced values between start and stop
arr = np.linspace(1, 10, num=5) # generate 5 evenly spaced values between 1 and 10
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# logspace(start, stop(included in output), num=50) -> generate num evenly spaced values between start and stop in log scale
arr = np.logspace(1, 10, num=5) # generate 5 evenly spaced values between 10^1 and 10^10 # here 10 is base

print(arr)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


### ndarray indexing and slicing

In [36]:
# indexing
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1[0])    # first element
print(arr1[1])    # second element

1
2


In [37]:
arr2 = [[1, 2, 3],
       [4, 5, 6],]
print(arr2[0][0])    # first row, first column

1


In [38]:
# changing value
print(arr1)
arr1[1] = 20
print(arr1)

[1 2 3 4 5]
[ 1 20  3  4  5]


In [39]:
# slicing

print(arr1[1:4])    # elements from index 1 to 3

[20  3  4]


In [ ]:
print(arr1[0:3:2])  # elements from index 0 to 2 with a step of 2 (0 and 2)

[1 3]


In [45]:
# 2d slicing

# arr[row_start:row_end:row_step, col_start:col_end:col_step]
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],])

print(arr2[0:2, 1:3])  # elements from rows 0 to 1 and columns 1 to 2

[[2 3]
 [5 6]]


In [47]:
print(arr2[1:])

[[4 5 6]
 [7 8 9]]


In [48]:
print(arr2[:, 1:])    # all rows and columns from index 1 to end

[[2 3]
 [5 6]
 [8 9]]


# advanced indexing & iteration

In [49]:
arr1= np.array([1, 2, 3, 4, 5])
arr1_slice = arr1[1:4]
# now if we change the value of arr1_slice, it will also change the value of arr1 because arr1_slice is a view of arr1
arr1_slice[0] = 20
print(arr1)    # arr1 is also changed because arr1_slice is a view of arr1

[ 1 20  3  4  5]


In [ ]:
# to avoid this we can use copy() method to create a copy of the array
arr1= np.array([1, 2, 3, 4, 5])
arr1_slice = arr1[1:4].copy()    # create a copy of the array
arr1_slice[0] = 20
print(arr1)    # no change now

[1 2 3 4 5]


In [53]:
# advanced indexing

arr = np.array([10,20,30,40,50])
print(arr[[2,3,4]])    # elements at index 2, 3 and 4

[30 40 50]


In [56]:
# boolean indexing
arr = np.array([10,20,30,40,50])
val = arr[arr > 25]
print(val)  

[30 40 50]


In [57]:
# iteration
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],])
for row in arr2:
    print(row)


[1 2 3]
[4 5 6]
[7 8 9]


In [58]:
for row in arr2:
    for col in row:
        print(col)

1
2
3
4
5
6
7
8
9


In [59]:
for i in np.nditer(arr2):
    print(i)

1
2
3
4
5
6
7
8
9
