# Numpy array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1, 100, size = (10,5))  # 10 rows(samples) and 5 columns(features)
print(arr.shape)

(10, 5)


In [4]:
# to change this shape:
arr = arr.reshape(5,10)    # reshape to 5 rows and 10 columns
print(arr.shape)

(5, 10)


In [8]:
# to make it 1D:
flatten = arr.flatten() # it flattens row wise. 1 row after another
print(arr)
print(flatten)
print(flatten.shape)
print(flatten.ndim)

[[15  1 10 59  9 24 30 74 61 35]
 [51 90 64 93 38 73 58 72 62  1]
 [40 83 52 62 51 88 88 87 26 45]
 [ 4 20 19 65 55 28  7  6 26 28]
 [93 23 82 91 40 35 93 96 28 14]]
[15  1 10 59  9 24 30 74 61 35 51 90 64 93 38 73 58 72 62  1 40 83 52 62
 51 88 88 87 26 45  4 20 19 65 55 28  7  6 26 28 93 23 82 91 40 35 93 96
 28 14]
(50,)
1


In [13]:
# column wise flattening:
flatten_col = arr.flatten(order='F') # it flattens column wise. 1 column after another
print(flatten_col)

[15 51 40  4 93  1 90 83 20 23 10 64 52 19 82 59 93 62 65 91  9 38 51 55
 40 24 73 88 28 35 30 58 88  7 93 74 72 87  6 96 61 62 26 26 28 35  1 45
 28 14]


In [10]:
# it can also be done by ravel:
flatten_ravel = arr.ravel()
print(flatten_ravel)

[15  1 10 59  9 24 30 74 61 35 51 90 64 93 38 73 58 72 62  1 40 83 52 62
 51 88 88 87 26 45  4 20 19 65 55 28  7  6 26 28 93 23 82 91 40 35 93 96
 28 14]


In [15]:
# to add two arrays:
a = np.random.randint(1,10, size=(2,3))
b = np.random.randint(10,20, size=(2,3))

print(a)
print(b)

[[2 9 2]
 [8 2 5]]
[[14 13 13]
 [14 14 19]]


In [16]:
# concatenate:
# row wise:
row_concat = np.concatenate((a,b), axis=0)
print(row_concat)

[[ 2  9  2]
 [ 8  2  5]
 [14 13 13]
 [14 14 19]]


In [17]:
# concatenate:
# column wise:
column_concat = np.concatenate((a,b), axis=1)
print(column_concat)

[[ 2  9  2 14 13 13]
 [ 8  2  5 14 14 19]]


row wise concatenate korte gele 2 ta array er column shonkha same thaka lage. <br>
column wise korte gele row shonkha same thaka lage

In [19]:
# transpose:
mat = np.array([[1,2,3],
        [4,5,6]])
mat_transpose = mat.T
print(mat_transpose)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
# array split:
arr = np.random.randint(1,100, size=(10,))
print(arr)

[53 10 52 63 55 93 43 17 77  9]


In [24]:
splitted_array = np.array_split(arr, 3) # it splits the array into 3 parts
print(splitted_array)

[array([53, 10, 52, 63], dtype=int32), array([55, 93, 43], dtype=int32), array([17, 77,  9], dtype=int32)]


# Arithmetic Operator and mathematical functions

In [25]:
x = [1,2,3,4,5,6,7,8,9,10]
y = [2,4,6,8,10,12,14,16,18,20]
add = x+y
print(add)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [26]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([2,4,6,8,10,12,14,16,18,20])
add = x+y
print(add)

[ 3  6  9 12 15 18 21 24 27 30]


In [27]:
sub = x-y
print(sub)

[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]


In [28]:
mul = x*y
print(mul)

[  2   8  18  32  50  72  98 128 162 200]


In [29]:
div = x/y
print(div)

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [30]:
remainder = x%y
print(remainder)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
# mathemical functions:
#trigonometrical functions:
sin = np.sin(x)
cos = np.cos(x)
#exponential functions:
exp = np.exp(x)
print(sin)
print(cos)
print(exp)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [33]:
# rad to degree:
deg = np.rad2deg(x)
print(deg)

[ 57.29577951 114.59155903 171.88733854 229.18311805 286.47889757
 343.77467708 401.07045659 458.3662361  515.66201562 572.95779513]


In [34]:
# logarithmic functions:
base_19_log = np.log(x) # natural log
base_10_log = np.log10(x) # log base 10

In [36]:
sqrt = np.sqrt(x)
print(sqrt)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [37]:
# np.all() -> shob true kina check kore
# np.any() -> kono ekta true kina check kore

greater_than = np.greater(x, 5) # check if elements of x are greater than 5
print(greater_than)

print(np.all(greater_than)) # check if all elements are greater than 5
print(np.any(greater_than)) # check if any element is greater than 5

[False False False False False  True  True  True  True  True]
False
True


# sorting


In [38]:
# inplace sorting:
arr = np.array([5,2,9,199,23])
arr2= arr.copy()


arr2.sort() # it sorts the array in place
print(arr2)

np.sort(arr) # it returns a sorted array but does not change the original array
print(arr)


[  2   5   9  23 199]
[  5   2   9 199  23]


In [39]:
twod_array = np.array([[5,2,9],
                    [199,23,1]])
# horizontal axis = 1
horizontal_sort = np.sort(twod_array, axis=1) # it sorts each row
print(horizontal_sort)

vertical_sort = np.sort(twod_array, axis=0) # it sorts each column
print(vertical_sort)

[[  2   5   9]
 [  1  23 199]]
[[  5   2   1]
 [199  23   9]]


# searching

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

#np.where() -> condition based selection
index = np.where(x==3) # return index
print(index)

(array([2]),)


In [ ]:
# change value:
x = np.where(x==3, 30, x) # if x is 3 change it to 30 else keep it as x
# now it will return array, not index
print(x)

[ 1  2 30  4  5  6  7  8  9 10]


In [49]:
x = np.array([[10,3,5],
              [8,4,9]])
index = np.where(x>5)
print(index)

(array([0, 1, 1]), array([0, 0, 2]))


ekhane output er 1st array holo x axis er index and 2nd arry y axis er index

# counting:

In [52]:
# max value index:
x = np.array([[10,300,5],
              [8,4,900]])

max_index = np.argmax(x)
print(max_index)

5


In [53]:
# min value index:
min_index = np.argmin(x)
print(min_index)

4


In [54]:
a = np.random.randint(1,100,size=(100,))

In [55]:
value_greater_than_sixty = np.count_nonzero(a>50)
print(value_greater_than_sixty)

47


In [56]:
# unique values:
unique_values = np.unique(a)
print(unique_values)

[ 1  3  6  7  8  9 10 11 14 15 16 17 18 20 21 22 23 25 28 29 31 32 33 36
 38 39 41 42 43 44 45 47 48 49 51 52 53 54 55 56 57 60 62 63 65 66 67 69
 71 73 75 76 77 79 83 86 87 89 90 92 94 95 98 99]


In [57]:
num_of_unique_values = len(unique_values)
print(num_of_unique_values)

64


In [59]:
unique_values, count = np.unique(a, return_counts=True) # it returns unique values and their counts
print(unique_values)
print(count)

[ 1  3  6  7  8  9 10 11 14 15 16 17 18 20 21 22 23 25 28 29 31 32 33 36
 38 39 41 42 43 44 45 47 48 49 51 52 53 54 55 56 57 60 62 63 65 66 67 69
 71 73 75 76 77 79 83 86 87 89 90 92 94 95 98 99]
[2 1 2 1 1 2 2 1 1 1 1 4 2 1 1 2 1 2 1 2 1 1 1 1 1 1 2 6 1 1 1 1 2 2 2 1 1
 1 2 3 1 3 1 1 1 1 2 1 2 2 1 2 1 2 2 1 2 1 1 3 1 1 1 3]


# statistical Method

In [60]:
data = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=1) # it reads the csv file and returns a numpy array
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [ ]:
# math minimum:
math_marks = data[:,0]      # returns 1D array
math_marks2 = data[::,:1]   # returns 2D array
print(math_marks)
print(math_marks2)

[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
 62. 95.]
[[78.]
 [56.]
 [89.]
 [45.]
 [70.]
 [92.]
 [61.]
 [55.]
 [88.]
 [74.]
 [66.]
 [80.]
 [59.]
 [73.]
 [91.]
 [68.]
 [77.]
 [84.]
 [62.]
 [95.]]


In [ ]:
max_math_marks = np.max(math_marks2)
print(max_math_marks)

min_math_marks = np.min(math_marks2)
print(min_math_marks)

avg_math_marks = np.mean(math_marks2)
print(avg_math_marks)

median_math_marks = np.median(math_marks2)
print(median_math_marks)


95.0
45.0
73.15
73.5


In [68]:
# standard deviation:
std_math_marks = np.std(math_marks2)
print(std_math_marks)

13.788672887555204


# Linear Algebra

In [69]:
# dot product

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
C = np.dot(A, B)
print(C)

[[ 58  64]
 [139 154]]


In [71]:
sq_matrix = np.array([[1,2],
                      [3,4]])
determinant = np.linalg.det(sq_matrix)
print(determinant)

-2.0000000000000004


In [72]:
# rank:
rank = np.linalg.matrix_rank(sq_matrix)
print(rank)

2
