In [1]:
# 2d array
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])

In [3]:
# 3d array:
arr3d = np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
print(arr3d)
print(arr3d.ndim)
print(arr3d.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [ ]:
arr_zero = np.zeros((3,3))
print(arr_zero)

arr_one = np.ones((2,5))
print(arr_one)

arr_seven = np.full((4,5),7) 
# full used to create an array with a specific value
# here 4 is the number of rows and 5 is the number of columns and 7 is the value that will be filled in the array
print(arr_seven)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
arr = np.arange(10,51,2) # arrange -> works like range but returns an array instead of a list
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [13]:
mat = np.array([[0,1,2,3],
                [4,5,6,7],
                [8,9,10,11],
                [12,13,14,15]])
print(mat[0,:]) # first row
print(mat[:,-1]) # last column
print(mat[1:3,1:3]) # submatrix


[0 1 2 3]
[ 3  7 11 15]
[[ 5  6]
 [ 9 10]]
