# Ndarray from scratch

In [8]:
import numpy as np
arr = np.zeros((2,3), dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [15]:
arr3 = np.array([[
                  [1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                
                 [[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]
])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
arr_like = np.zeros_like(arr3) # arr3 এর মতো shape এবং dtype এর zeros array তৈরি করবে
print(arr_like)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [17]:
arr = np.ones_like(arr3) # arr3 এর মতো shape এবং dtype এর ones array তৈরি করবে
print(arr)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [29]:
arr = np.empty((3,3), dtype=int) # uninitialized array তৈরি করবে, এর মান অজানা হবে
print(arr)

[[25895968444448860 23925768161198147 32370111954616435]
 [28429466574585948 31525476570497138 32651513914720368]
 [31244048838426721      463862825059                 0]]


In [31]:
arr = np.empty_like(arr3) # arr3 এর মতো shape এবং dtype এর empty array তৈরি করবে
print(arr)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [32]:
arr = np.full((3,5),10) # 3 rows এবং 5 columns এর array তৈরি করবে, যার সব মান 10 হবে
print(arr)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [34]:
arr = np.full((3,5), np.inf) # 3 rows এবং 5 columns এর array তৈরি করবে, যার সব মান infinity হবে
print(arr)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


# matrix for linear algebra

- diagonal matrix
- identity matrix

In [36]:
diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [38]:
identity_mat = np.eye(3) # 3x3 identity matrix তৈরি করবে
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
mat = np.eye(2,4)   # 4 rows এবং 5 columns এর array তৈরি করবে, যার diagonal এ 1 থাকবে এবং বাকি সব মান 0 হবে
print(mat)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
mat = np.eye(3,3,-1) 
print(mat)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
mat = np.eye(4,4,1) # not in diagonal
print(mat)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


# preprocessing a dataset using numpy

In [49]:
import numpy as np

#dataset
data = np.array([
    [9.5, 0.5, 95.5],
    [8.2, 1.2, 86.4],
    [7.8, 1.5, 82.1],
    [7.0, 1.0, 81.0],
    [6.5, 2.0, 74.5],
    [5.0, 1.5, 70.0],
    [4.5, 3.0, 60.5],
    [3.0, 2.5, 55.0],
    [2.0, 4.0, 44.0],
    [1.5, 4.5, 39.5]
])


In [50]:
# randomize:

# shuffle the dataset
random_index = np.random.choice(10, size=10, replace=False)    # 0 থেকে 9 পর্যন্ত সংখ্যা থেকে 10টি সংখ্যা নির্বাচন করবে, যেখানে প্রতিটি সংখ্যা একবারই নির্বাচিত হবে
print(random_index)

[8 3 2 5 6 1 4 9 7 0]


In [ ]:
data = data[random_index]   # random_index এর মাধ্যমে data array কে shuffle করবে
print(data)

[[ 2.   4.  44. ]
 [ 7.   1.  81. ]
 [ 7.8  1.5 82.1]
 [ 5.   1.5 70. ]
 [ 4.5  3.  60.5]
 [ 8.2  1.2 86.4]
 [ 6.5  2.  74.5]
 [ 1.5  4.5 39.5]
 [ 3.   2.5 55. ]
 [ 9.5  0.5 95.5]]


In [52]:
# feature extraction:

X = data[:,0:2] # প্রথম 2 column কে X (features) তে assign করবে
y = data[:, -1] # শেষ column কে y (target) তে assign করবে



In [55]:
# train, test, split:

train_index = int(len(data) * 0.8) # dataset এর 80% কে training set এবং বাকি 20% কে test set হিসেবে ভাগ করবে

X_train = X[:train_index,:] # প্রথম 80% rows কে X_train এ assign করবে
y_train = y[:train_index] # প্রথম 80% rows কে y_train এ assign করবে

X_test = X[train_index:,:] # শেষ 20% rows কে X_test এ assign করবে
y_test = y[train_index:] # শেষ 20% rows কে y_test এ assign করবে


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

