In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
# scaling

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[ 0.38022148,  3.32491119,  0.46622593, ...,  1.30291261,
         1.0374922 ,  2.15937211],
       [-0.19101222,  0.36024342, -0.1532392 , ...,  1.67091936,
        -0.14936386,  1.37463418],
       [ 0.91801712,  4.65598651,  0.85895873, ...,  1.38134028,
        -0.07192361,  0.06831104],
       ...,
       [-0.78732448,  0.46263383, -0.79780685, ..., -0.48614319,
        -0.11232722,  0.26656062],
       [-0.558831  , -0.28900486, -0.56257205, ..., -0.87647167,
        -0.82444085, -0.38424084],
       [-1.80412048,  1.43534272, -1.77518518, ..., -0.98053915,
        -0.17798308,  1.34513275]])

In [ ]:
X_test

array([[ 0.02354873,  0.56967835,  0.0585126 , ...,  0.44774937,
         1.17048741,  1.03831792],
       [-0.65914521, -0.6264278 , -0.53423051, ...,  1.07818717,
         4.84553248,  1.13272248],
       [ 0.82884893, -0.66831478,  0.96422732, ...,  2.11132089,
         1.9701422 ,  1.30383075],
       ...,
       [-0.64799919, -0.07724287, -0.67512846, ..., -0.69201582,
        -0.60727144, -0.22847331],
       [-0.18543921, -1.52699799, -0.26296146, ..., -1.40133376,
        -1.05844509, -1.29111467],
       [-0.26903439, -0.42862814, -0.32612261, ..., -0.98506383,
        -0.21670321, -0.69754598]])

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,

In [ ]:
# converting all to tensors

X_train = torch.from_numpy(X_train)
X_test= torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)


In [ ]:
# defining model

class MyModel():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)
    loss = -(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred)).mean()
    return loss


In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
model = MyModel(X_train)
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train)
  #loss
  loss = model.loss_function(y_pred, y_train)
  #backward pass
  loss.backward()
  #update weights
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 4.035687285932397
Epoch: 2, Loss: 3.9205585582949336
Epoch: 3, Loss: 3.803157899193285
Epoch: 4, Loss: 3.678354701375567
Epoch: 5, Loss: 3.544429451164952
Epoch: 6, Loss: 3.4071707370630815
Epoch: 7, Loss: 3.2653256070231738
Epoch: 8, Loss: 3.1205857201631138
Epoch: 9, Loss: 2.974004073310287
Epoch: 10, Loss: 2.8212343152810235
Epoch: 11, Loss: 2.6651442893399073
Epoch: 12, Loss: 2.5027912164140513
Epoch: 13, Loss: 2.3394916539057533
Epoch: 14, Loss: 2.176210391440784
Epoch: 15, Loss: 2.0119723304179553
Epoch: 16, Loss: 1.8492497611198548
Epoch: 17, Loss: 1.6950817045354791
Epoch: 18, Loss: 1.5468324695857292
Epoch: 19, Loss: 1.4109488274915578
Epoch: 20, Loss: 1.2890393546960646
Epoch: 21, Loss: 1.1825149958835175
Epoch: 22, Loss: 1.0923129756778487
Epoch: 23, Loss: 1.0185766402854055
Epoch: 24, Loss: 0.9604162866085882
Epoch: 25, Loss: 0.9159076491044359
